name: 'VHS Action'
description: 'Run VHS to render terminal videos'
branding:
  icon: film
  color: purple
inputs:
  version:
    description: VHS version
    default: latest
  path:
    description: 'The tape file path'
    default: ''
  working-directory:
    description: 'Working directory where the tape files are located'
    default: ''
  token:
    description: Used to pull VHS from Github
    default: ${{ github.token }}
  install-fonts:
    description: Install extra fonts
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
